### ISSUE TITLE
Packing files into one executable file

### ISSUE THREAD

**Issue by hieunc229** [neutralinojs/neutralinojs-typescript#6]
Hey Shalitha, thanks for the project, I love its simplicity.

I wanted to pack files into one executable file (on MacOS). I looked around and see a suggestion using electron packaging but don't really know how to do it with neutralino.

Is there a way I could pack files into one executable file? (I don't mind using any library)

Many thanks!

**Comment by shalithasuranga** [comment]
Hey.. Thank you very much for trying Neutralinojs. Please check the build command docs: https://neutralino.js.org/docs/developer-environment/cli#neu-build---release
